[package]
name = "acurite-weather"
version = "0.2.0"
authors = ["dblue <dblue@deloitte.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.7.0", features = ["full"] }
async-trait = "0.1.50"
chrono = "0.4.19"
hidapi = "1.2.6"
influxdb = { version = "0.4.0", features = ["derive"] }
