[package]
name = "acurite-weather"
version = "0.1.0"
authors = ["dblue <dblue@deloitte.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = { version = "1.9.0", features = ["attributes"] }
async-trait = "0.1.42"
chrono = "0.4.19"
hidapi = "1.2.5"
influxdb = { version = "0.3.0", features = ["derive"] }
