version: "3.9"

services:
  influxdb:
    container_name: influxdb
    image: influxdb:1.8.6
    ports:
      - 8086:8086
    environment:
      - INFLUXDB_DB=weather
    volumes:
      - influxdb_data:/var/lib/influxdb

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  influxdb_data:
  grafana_data:
