version: "3.9"

services:
  influxdb:
    container_name: influxdb
    image: influxdb:1.8.6
    ports:
      - 8086:8086
    environment:
      - INFLUXDB_DB=weather
    volumes:
      - influxdb_data:/var/lib/influxdb

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    depends_on:
      - influxdb
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on: 
      - influxdb

  nginx:
    container_name: nginx
    image: nginx:1.21.0
    ports: 
      - 8080:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/weather.conf
    depends_on: 
      - grafana

volumes:
  influxdb_data:
  grafana_data:
