version: '3.9'

services:
  # weather:
  #   container_name: weather
  #   build: .
  #   depends_on:
  #     - influxdb
  #   environment:
  #     - INFLUXDB_HOST=influxdb
  #   devices:
  #     - /dev/ttyUSB0:/dev/ttyUSB0

  influxdb:
    container_name: influxdb
    image: influxdb:latest
    ports:
      - 8086:8086
    environment:
      - INFLUXDB_DB=weather
    volumes:
      - influxdb_data:/var/lib/influxdb

  chronograf:
    container_name: chronograf
    image: chronograf:latest
    depends_on:
      - influxdb
    ports:
      - 8888:8888
    volumes:
      - chronograf_data:/var/lib/chronograf
    environment:
      - INFLUXDB_URL=http://influxdb:8086

volumes:
  influxdb_data:
  chronograf_data:
